# Site Settings
title: My Minimal Site
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # Try "air" or "contrast" to see if it changes

# Build Settings
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache

# Basic Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: trues